"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
// import { useClient } from 'next/react';


const inter = Inter({ subsets: ['latin'] })
// export const metadata = {
//   title: 'Insurance Web',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  // useClient()
  return (
    <>
    <Navbar />
    {children}
    </>
  )
}
